name = "Verilog"
uuid = "54c5fdc4-1d70-4d58-a050-8ed29bc6e0c3"
authors = ["Guilhem Ribeill <guilhem.ribeill@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
